# Oracle Autonomous Database (OCI) in production — SQLite fallback for local demo
import os
import sqlite3

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

try:
    import oracledb
except ImportError:
    oracledb = None

DB_PATH = "db/quantum_twin.db"
_active_backend: str | None = None

ORACLE_TABLES = [
    """
    CREATE TABLE telemetry_data (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lap NUMBER,
        driver VARCHAR2(100),
        compound VARCHAR2(50),
        tyre_life NUMBER,
        lap_time NUMBER,
        position NUMBER,
        stint NUMBER,
        speed NUMBER,
        throttle NUMBER,
        brake NUMBER,
        rpm NUMBER,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE superclipping_predictions (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        predicted_laptime NUMBER,
        status VARCHAR2(100),
        velocidad NUMBER,
        soc_bateria NUMBER,
        mguk_kw NUMBER,
        throttle_pct NUMBER,
        aero_mode NUMBER,
        temp_bateria NUMBER,
        "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE alert_history (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        severity VARCHAR2(50),
        title VARCHAR2(500),
        description VARCHAR2(2000),
        "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE classification_results (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ers_status_predicted VARCHAR2(50),
        prob_normal NUMBER,
        prob_alerta NUMBER,
        prob_critico NUMBER,
        lap NUMBER,
        race VARCHAR2(200),
        "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE cluster_assignments (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cluster_id NUMBER,
        cluster_label VARCHAR2(500),
        tyre_life NUMBER,
        race_progress NUMBER,
        lap NUMBER,
        "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE safety_events (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        is_critical NUMBER,
        probability_critical NUMBER,
        kernel VARCHAR2(50),
        lap NUMBER,
        ers_risk NUMBER,
        "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
]

SQLITE_INIT_SCRIPT = """
    CREATE TABLE IF NOT EXISTS telemetry_data (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        lap INTEGER, driver TEXT, compound TEXT,
        tyre_life INTEGER, lap_time REAL,
        position INTEGER, stint INTEGER,
        speed REAL, throttle REAL, brake REAL, rpm REAL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS superclipping_predictions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        predicted_laptime REAL, status TEXT,
        velocidad REAL, soc_bateria REAL, mguk_kw REAL,
        throttle_pct REAL, aero_mode INTEGER, temp_bateria REAL,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS alert_history (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        severity TEXT, title TEXT, description TEXT,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS classification_results (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        ers_status_predicted TEXT,
        prob_normal REAL, prob_alerta REAL, prob_critico REAL,
        lap INTEGER, race TEXT,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS cluster_assignments (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        cluster_id INTEGER, cluster_label TEXT,
        tyre_life REAL, race_progress REAL, lap INTEGER,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS safety_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        is_critical INTEGER, probability_critical REAL,
        kernel TEXT, lap INTEGER, ers_risk REAL,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
"""


def get_db_status() -> str:
    """Return active database engine: 'oracle' or 'sqlite_fallback'."""
    _resolve_backend()
    return _active_backend or "sqlite_fallback"


def _oracle_configured() -> bool:
    required = ("ORACLE_USER", "ORACLE_PASSWORD", "ORACLE_DSN", "ORACLE_WALLET_DIR")
    return all(os.getenv(key) for key in required) and oracledb is not None


def _wallet_dir() -> str:
    wallet = os.getenv("ORACLE_WALLET_DIR", "wallet")
    if not os.path.isabs(wallet):
        wallet = os.path.join(os.path.dirname(__file__), wallet)
    return wallet


def _connect_oracle():
    wallet_dir = _wallet_dir()
    if not os.path.isdir(wallet_dir):
        raise FileNotFoundError(f"Oracle wallet directory not found: {wallet_dir}")

    kwargs = {
        "user": os.environ["ORACLE_USER"],
        "password": os.environ["ORACLE_PASSWORD"],
        "dsn": os.environ["ORACLE_DSN"],
        "config_dir": wallet_dir,
        "wallet_location": wallet_dir,
    }
    wallet_password = os.getenv("ORACLE_WALLET_PASSWORD")
    if wallet_password:
        kwargs["wallet_password"] = wallet_password

    return oracledb.connect(**kwargs)


def _connect_sqlite():
    os.makedirs(os.path.dirname(DB_PATH) or ".", exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def _resolve_backend():
    global _active_backend
    if _active_backend is not None:
        return

    if not _oracle_configured():
        if oracledb is None:
            print(
                "WARNING: oracledb not installed or Oracle env vars missing. "
                "Using SQLite fallback at db/quantum_twin.db"
            )
        else:
            print(
                "WARNING: Oracle credentials/wallet not configured. "
                "Using SQLite fallback at db/quantum_twin.db"
            )
        _active_backend = "sqlite_fallback"
        return

    try:
        conn = _connect_oracle()
        conn.close()
        _active_backend = "oracle"
        print(f"Oracle Autonomous Database connected (DSN: {os.environ['ORACLE_DSN']})")
    except Exception as exc:
        print(
            f"WARNING: Oracle connection failed ({exc}). "
            "Using SQLite fallback at db/quantum_twin.db"
        )
        _active_backend = "sqlite_fallback"


def get_connection():
    _resolve_backend()
    if _active_backend == "oracle":
        return _connect_oracle()
    return _connect_sqlite()


def _init_oracle(conn):
    cursor = conn.cursor()
    for ddl in ORACLE_TABLES:
        try:
            # Oracle Autonomous Database (OCI) in production
            cursor.execute(ddl)
        except oracledb.DatabaseError as exc:
            if exc.args[0].code != 955:  # ORA-00955: name already used
                raise
    conn.commit()
    cursor.close()


def _init_sqlite(conn):
    # Oracle Autonomous Database (OCI) in production
    conn.executescript(SQLITE_INIT_SCRIPT)
    conn.commit()


def init_db():
    conn = get_connection()
    try:
        if _active_backend == "oracle":
            _init_oracle(conn)
        else:
            _init_sqlite(conn)
    finally:
        conn.close()


def insert_prediction(data: dict):
    conn = get_connection()
    try:
        cursor = conn.cursor()
        # Oracle Autonomous Database (OCI) in production
        cursor.execute(
            """
            INSERT INTO superclipping_predictions
            (predicted_laptime, status, velocidad, soc_bateria, mguk_kw,
             throttle_pct, aero_mode, temp_bateria)
            VALUES (:predicted_laptime, :status, :velocidad, :soc_bateria, :mguk_kw,
                    :throttle_pct, :aero_mode, :temp_bateria)
            """,
            data,
        )
        conn.commit()
        cursor.close()
    finally:
        conn.close()


def insert_alert(data: dict):
    conn = get_connection()
    try:
        cursor = conn.cursor()
        # Oracle Autonomous Database (OCI) in production
        cursor.execute(
            """
            INSERT INTO alert_history (severity, title, description)
            VALUES (:severity, :title, :description)
            """,
            data,
        )
        conn.commit()
        cursor.close()
    finally:
        conn.close()


def _rows_to_dicts(cursor, rows) -> list[dict]:
    columns = [col[0].lower() for col in cursor.description]
    result = []
    for row in rows:
        item = {}
        for col, val in zip(columns, row):
            if hasattr(val, "isoformat"):
                val = val.isoformat()
            item[col] = val
        result.append(item)
    return result


def get_recent_predictions(limit=10):
    conn = get_connection()
    try:
        if _active_backend == "oracle":
            cursor = conn.cursor()
            # Oracle Autonomous Database (OCI) in production
            cursor.execute(
                """
                SELECT * FROM superclipping_predictions
                ORDER BY "timestamp" DESC
                FETCH FIRST :lim ROWS ONLY
                """,
                lim=limit,
            )
            rows = cursor.fetchall()
            result = _rows_to_dicts(cursor, rows)
            cursor.close()
            return result

        # Oracle Autonomous Database (OCI) in production
        rows = conn.execute(
            "SELECT * FROM superclipping_predictions ORDER BY timestamp DESC LIMIT ?",
            (limit,),
        ).fetchall()
        return [dict(row) for row in rows]
    finally:
        conn.close()


def get_recent_alerts(limit=10):
    conn = get_connection()
    try:
        if _active_backend == "oracle":
            cursor = conn.cursor()
            # Oracle Autonomous Database (OCI) in production
            cursor.execute(
                """
                SELECT * FROM alert_history
                ORDER BY "timestamp" DESC
                FETCH FIRST :lim ROWS ONLY
                """,
                lim=limit,
            )
            rows = cursor.fetchall()
            result = _rows_to_dicts(cursor, rows)
            cursor.close()
            return result

        # Oracle Autonomous Database (OCI) in production
        rows = conn.execute(
            "SELECT * FROM alert_history ORDER BY timestamp DESC LIMIT ?",
            (limit,),
        ).fetchall()
        return [dict(row) for row in rows]
    finally:
        conn.close()


def insert_classification(data: dict):
    """Persiste resultado del Árbol de Decisión (ERS_status)."""
    conn = get_connection()
    try:
        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT INTO classification_results
            (ers_status_predicted, prob_normal, prob_alerta, prob_critico, lap, race)
            VALUES (:ers_status_predicted, :prob_normal, :prob_alerta, :prob_critico,
                    :lap, :race)
            """,
            data,
        )
        conn.commit()
        cursor.close()
    finally:
        conn.close()


def insert_cluster_assignment(data: dict):
    """Persiste asignación de cluster K-Means."""
    conn = get_connection()
    try:
        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT INTO cluster_assignments
            (cluster_id, cluster_label, tyre_life, race_progress, lap)
            VALUES (:cluster_id, :cluster_label, :tyre_life, :race_progress, :lap)
            """,
            data,
        )
        conn.commit()
        cursor.close()
    finally:
        conn.close()


def insert_safety_event(data: dict):
    """Persiste detección SVM de evento crítico."""
    conn = get_connection()
    try:
        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT INTO safety_events
            (is_critical, probability_critical, kernel, lap, ers_risk)
            VALUES (:is_critical, :probability_critical, :kernel, :lap, :ers_risk)
            """,
            data,
        )
        conn.commit()
        cursor.close()
    finally:
        conn.close()
